// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub logs: ::prost::alloc::vec::Vec<super::super::sf::ethereum::r#type::v2::Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Calls {
    #[prost(message, repeated, tag="1")]
    pub calls: ::prost::alloc::vec::Vec<super::super::sf::ethereum::r#type::v2::Call>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventsCalls {
    #[prost(message, optional, tag="1")]
    pub events: ::core::option::Option<Events>,
    #[prost(message, optional, tag="2")]
    pub calls: ::core::option::Option<Calls>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoveredCurve {
    #[prost(bytes="vec", tag="1")]
    pub curve: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub quote_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub creator: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="5")]
    pub curve_allocation: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub liquidity_reserve: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub starting_price: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub slope: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub graduation_threshold: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub token_decimals: u32,
    #[prost(uint64, tag="11")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="12")]
    pub transaction_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="13")]
    pub ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoveredCurves {
    #[prost(message, repeated, tag="1")]
    pub curves: ::prost::alloc::vec::Vec<DiscoveredCurve>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CurveActivity {
    #[prost(string, tag="1")]
    pub event_type: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub canonical_trade: bool,
    #[prost(bytes="vec", tag="3")]
    pub curve: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub quote_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="6")]
    pub token_decimals: u32,
    #[prost(bytes="vec", tag="7")]
    pub actor: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="8")]
    pub token_amount: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub curve_quote: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub protocol_fee: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub gross_quote_in: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub net_quote_out: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub tokens_sold_after: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub quote_reserve_after: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub gross_quote_limit: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub actual_quote_in: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub refund_quote: ::prost::alloc::string::String,
    #[prost(string, tag="18")]
    pub allocation: ::prost::alloc::string::String,
    #[prost(uint32, tag="19")]
    pub previous_state: u32,
    #[prost(uint32, tag="20")]
    pub new_state: u32,
    #[prost(bytes="vec", tag="21")]
    pub graduation_router: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="22")]
    pub graduation_quote_amount: ::prost::alloc::string::String,
    #[prost(uint64, tag="23")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="24")]
    pub transaction_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="25")]
    pub ordinal: u64,
    #[prost(string, tag="26")]
    pub event_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CurveActivities {
    #[prost(message, repeated, tag="1")]
    pub activities: ::prost::alloc::vec::Vec<CurveActivity>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoveredAmmPool {
    #[prost(bytes="vec", tag="1")]
    pub pair: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub curve: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub quote_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="5")]
    pub token_amount: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub quote_amount: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub liquidity: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="9")]
    pub transaction_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="10")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="11")]
    pub token0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="12")]
    pub token1: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="13")]
    pub token_is_token0: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoveredAmmPools {
    #[prost(message, repeated, tag="1")]
    pub pools: ::prost::alloc::vec::Vec<DiscoveredAmmPool>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AmmActivity {
    #[prost(string, tag="1")]
    pub event_type: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub pair: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub curve: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub quote_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="8")]
    pub amount0: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub amount1: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub amount0_in: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub amount1_in: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub amount0_out: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub amount1_out: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub reserve0: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub reserve1: ::prost::alloc::string::String,
    #[prost(uint64, tag="16")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="17")]
    pub transaction_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="18")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="19")]
    pub token0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="20")]
    pub token1: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="21")]
    pub token_is_token0: bool,
    #[prost(string, tag="22")]
    pub token_amount: ::prost::alloc::string::String,
    #[prost(string, tag="23")]
    pub quote_amount: ::prost::alloc::string::String,
    #[prost(string, tag="24")]
    pub token_amount_in: ::prost::alloc::string::String,
    #[prost(string, tag="25")]
    pub quote_amount_in: ::prost::alloc::string::String,
    #[prost(string, tag="26")]
    pub token_amount_out: ::prost::alloc::string::String,
    #[prost(string, tag="27")]
    pub quote_amount_out: ::prost::alloc::string::String,
    #[prost(string, tag="28")]
    pub token_reserve: ::prost::alloc::string::String,
    #[prost(string, tag="29")]
    pub quote_reserve: ::prost::alloc::string::String,
    #[prost(string, tag="30")]
    pub event_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AmmActivities {
    #[prost(message, repeated, tag="1")]
    pub activities: ::prost::alloc::vec::Vec<AmmActivity>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketActivity {
    #[prost(string, tag="1")]
    pub market_stage: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub event_type: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub canonical_trade: bool,
    #[prost(bytes="vec", tag="4")]
    pub market: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub curve: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="6")]
    pub pair: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub quote_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="9")]
    pub block_number: u64,
    #[prost(bytes="vec", tag="10")]
    pub transaction_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="11")]
    pub ordinal: u64,
    #[prost(message, optional, tag="12")]
    pub curve_activity: ::core::option::Option<CurveActivity>,
    #[prost(message, optional, tag="13")]
    pub amm_activity: ::core::option::Option<AmmActivity>,
    #[prost(string, tag="14")]
    pub event_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketActivities {
    #[prost(message, repeated, tag="1")]
    pub activities: ::prost::alloc::vec::Vec<MarketActivity>,
}
// @@protoc_insertion_point(module)
